---
title: "Case Study 09"
author: Sean Colby
date: August 1, 2020
output: github_document
---
```{r}
#Install New Libraries
install.packages("rnoaa")
install.packages("ggmap")

#Load Libraries
library(sf)
library(tidyverse)
library(ggmap)
library(rnoaa)
library(spData)
data(world)
data(us_states)
```
```{r}
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NA.list.v04r00.points.zip"
tdir=tempdir()
download.file(dataurl,destfile=file.path(tdir,"temp.zip"))
unzip(file.path(tdir,"temp.zip"),exdir = tdir)
list.files(tdir)

storm_data <- read_sf(list.files(tdir,pattern=".shp",full.names = T))
```

```{r}
#Filter and Wrangle the Data
storms<- storm_data%>% filter(SEASON> 1949)%>%
mutate_if(is.numeric, function(x) ifelse(x==-999.0,NA,x))%>%
  mutate(decade=(floor(year/10)*10))
#Box it
  region<-st_bbox(storms)
```

```{r}
#Set up a Base Map
ggplot()+
  geom_sf(data= world, inherit.aes = F)+
  facet_wrap(~decade)+
  stat_bin2d(data=storms, aes(y=st_coordinates(storms)[,2], x=st_coordinates(storms)[,1]),bins=100)+
  scale_fill_distiller(palette="YlOrRd", trans="log", direction=-1, breaks = c(1,10,100,1000))+
  coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)])
```

```{r}
#Calculate Table of States w/ most storms

#Change CRS
states<- st_transform(us_states, crs= 4326)%>%
  select(state=NAME)

#Spatial Join
storm_states <- st_join(storms, states, join = st_intersects,left = F)%>% 
  group_by(state)%>%
summarize(storms=length(unique(NAME)))%>%
  arrange(desc(storms))%>%
  slice(1:5)

#Show The Table
view(storm_states)
```


